name: "Hola Mundo"

on: [push]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: "Imprimir Hola Mundo"
              run: echo "Hola Mundo"

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: "ls"
              run: ls -la