name: "Hola Mundo"

on: [push]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: "Imprimir Hola Mundo"
              run: echo "Hola Mundo"

            - name: "Touch file"
              run: touch hola.txt

            - name: "Set text"
              run: echo "Hola Mundo" >> hola.txt

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: "ls"
              run: ls -la